include:
  - project: 'my-group/aws'
    file: '/aws-assume-role.yml'

variables:
  TF_USERNAME: $GITLAB_USER_LOGIN
  TF_PASSWORD: $GITLAB_ACCESS_TOKEN
  TF_STATE_NAME: default
  TF_ADDRESS: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}

default:
  image:
    name: "$CI_TEMPLATE_REGISTRY_HOST/gitlab-org/terraform-images/releases/1.5:v1.8.0"

cache:
  key: "${TF_STATE_NAME}"
  paths:
    - .terraform

stages:
  - init
  - validate
  - plan
  - deploy
  - cleanup

test_access:
  extends: .assume_role_template
  stage: init
  image:
    name: amazon/aws-cli:latest
    entrypoint: 
      - '/usr/bin/env'
  script:
     - |
      if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
        echo "One or more AWS credentials are missing."
        exit 1
      fi
  when: manual

init:
  stage: init
  before_script:
    - terraform --version
    - echo ${TF_USERNAME}
    - echo ${TF_PASSWORD}
    - echo ${TF_STATE_NAME}
    - echo ${TF_ADDRESS}
  script:
    - |
      terraform init -reconfigure \
        -backend-config="address=${TF_ADDRESS}" \
        -backend-config="lock_address=${TF_ADDRESS}/lock" \
        -backend-config="unlock_address=${TF_ADDRESS}/lock" \
        -backend-config="username=${TF_USERNAME}" \
        -backend-config="password=${TF_PASSWORD}" \
        -backend-config="lock_method=POST" \
        -backend-config="unlock_method=DELETE" \
        -backend-config="retry_wait_min=5"
  when: manual

fmt:
  stage: validate
  allow_failure: true
  script:
    - ls -la
    - terraform fmt -check

validate:
  stage: validate
  allow_failure: true
  script:
    - terraform validate

aws_credentials:
  stage: plan
  extends: .assume_role_dotenv_template

plan:
  stage: plan
  needs: [aws_credentials]
  script:
    - |
      if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
        echo "One or more AWS credentials are missing."
        exit 1
      fi
    - terraform plan -out plan.cache
    - terraform show -json plan.cache
  artifacts:
    name: plan
    paths:
      - plan.cache

refresh:
  stage: plan
  needs: [aws_credentials]
  script:
    - terraform refresh
  when: manual

apply:
  stage: deploy
  needs: [aws_credentials, plan]
  script:
    - |
      if [ -z "${AWS_ACCESS_KEY_ID}" ] || [ -z "${AWS_SECRET_ACCESS_KEY}" ] || [ -z "${AWS_SESSION_TOKEN}" ]; then
        echo "One or more AWS credentials are missing."
        exit 1
      fi
    - terraform apply -auto-approve plan.cache
  environment:
    name: $TF_STATE_NAME
  when: manual

report:
  stage: deploy
  needs: [apply]
  script:
    - echo $TF_ADDRESS
    - echo $TF_STATE_NAME
    - terraform output
    - terraform output -json > output.json
  environment:
    name: $TF_STATE_NAME
  when: manual
  artifacts:
    paths:
      - output.json
    expire_in: 365 days

cleanup:
  stage: cleanup
  script:
    - terraform destroy -auto-approve
  environment:
    name: $TF_STATE_NAME
  when: manual
